### ISSUE TITLE
Ethernet switch failed, I replaced it, now the SPAN integration says, "Failed setup, will retry: Error communicating with API: All connection attempts failed"

### ISSUE THREAD

**Issue by Obioban** [SpanPanel/Span#15]
Longer, fuller story:
SPAN panel is connected to my network via a switch in my utility room. It failed. I replaced it. 
SPAN panel can talk to the internet (the app can see it) and the Tesla system (it can see battery levels, etc). 

Home assistant can ping the SPAN panel and get a response there. 

Some other devices were having similar issues, but they were all resolved by reboot those devices. 

Since there's no way (that I know of, at least) to do a reboot myself of the span panel, I called them and had them do it-- and they insisted on running a software update on the panel first. 

So, in net, two possible issues:
1) did the most recent span software update break the integration? 
2) If not, what can I do to get the panel back into home assistant? 

Thanks!

**Comment by cayossarian** [comment]
@Obioban if SPAN replaced the panel it will no longer honor your previous authentication.  

If the HA SPAN Integration is still installed in HA you would need to start over by deleting it completely, let it be rediscovered, and authenticate again.

**Comment by Obioban** [comment]
The span panel wasn't replaced-- the ethernet switch I plug it into for network access was replaced. 

SPAN panel software version is listed as spanos2/r202429/04-- is that what you're asking for?

**Comment by Obioban** [comment]
Yeah, a full reboot of HA was one of the first things I tried-- no improvement. 

Switch is a Unifi Flex switch-- plugged into a 48 port pro poe (unifi) switch, plugged into a dream machine pro.

**Comment by cayossarian** [comment]
If your SPAN panel IP is the same as before you changed the switch you should be able to invoke the status directly from a terminal (from the terminal in HA or a computer connected to the same switch that HA uses):

curl -v http://192.168.1.60/api/v1/status

If the IP has changed then the SPAN HACs integration would need to be removed and reinstalled (current version is 0.0.12).

**Comment by Obioban** [comment]
Seems like all is where in curl?

<img width="708" alt="Screenshot 2024-09-06 at 2 35 27 PM" src="https://github.com/user-attachments/assets/44c0babf-39df-423f-8043-58bba6568320">

**Comment by cayossarian** [comment]
Yes seems like the connection is fine.  Did uninstalling the integration and reinstalling work?

**Comment by Obioban** [comment]
I'm trying to avoid that option, as I have a whole boat load of automations that use SPAN that I don't want to lose

**Comment by cayossarian** [comment]
unless you have renamed entities within the SPAN integration that you subsequently used in your automation removing the SPAN HACs integration, adding it back, and reconfiguring it should not have any side-effects as the sensor entity names will be picked up again when you reinstall the integration.  

We can see from your curl response that the door state is unknown and the proximityProven is false.  Have you tried to open and close the door three times or are you using an auth token?  I assume you have our repository installed and the version is HAC's is 0.0.12?

**Comment by Obioban** [comment]
Ah, well, that's good news!

I was using the auth token. I am on version 0.0.12.

**Comment by Obioban** [comment]
Deleting it and re-adding it seems to have fixed everything, and left my automations intact as promised. Thanks!

**Comment by cayossarian** [comment]
You're welcome.  have a great day.
