### ISSUE TITLE
Span Door Sensor Inverted - Again

### ISSUE THREAD

**Issue by pavandave** [SpanPanel/Span#18]
It looks like SPAN pushed an update that fixes the initial door sensor issue when the firmware updated from spanos2/r202429/04 to  spanos2/r202433/03.

![image](https://github.com/user-attachments/assets/ad89ab3d-45b3-40d2-b055-73e2872a3152)

Issue was initially identified in  https://github.com/SpanPanel/Span/issues/11 and fixed. 

I know you're about to push a branch out, so would it be worth revert the change in this commit? If not I can pull and fix if I get a chance to, 
https://github.com/SpanPanel/Span/commit/6a88e0d623e77b0a30efd7fba14f7f3774dc0640

Thanks

**Comment by pavandave** [comment]
Looks like you beat me to it. It's resolved in this commit - https://github.com/SpanPanel/Span/commit/67a3b0818eddfa2adf9710ec39fe53b5d05780ae#diff-d222a0478dc4b822cf54af7174cd1f50967198fd12cd4290de5470a2dbbc9849

I'll close this out.

**Comment by cayossarian** [comment]
SPAN firmware flip at some point and the back?  A bit strange as I see even the name changed from Door to Cabinet Door

Reverted it again on our side

Ill push something out

**Comment by cayossarian** [comment]
i published a new beta if you have time to check it.

**Comment by pavandave** [comment]
Downloaded. Battery works as expected. Tested the config flow enable and
disable and everything works as expected.

**Comment by cayossarian** [comment]
Fixed in v1.0.2
